"""add is_active to clients

Revision ID: 750b270bffb9
Revises: fd43c31fb002
Create Date: 2026-04-07 00:00:23.970693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750b270bffb9'
down_revision = 'fd43c31fb002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
